Update branch-name-validator.yml

diff --git a/.github/workflows/branch-name-validator.yml b/.github/workflows/branch-name-validator.yml
--- a/.github/workflows/branch-name-validator.yml
+++ b/.github/workflows/branch-name-validator.yml
@@ -22,33 +22,11 @@ jobs:
           BRANCH_NAME="${GITHUB_REF#refs/heads/}"
           echo "Branch name: $BRANCH_NAME"
           
-          # التحقق من اسم الفرع باستخدام الـ regex
+          # التحقق من اسم الفرع باستخدام regex
           if [[ "$BRANCH_NAME" =~ ^(bugfix|hotfix|release)\/[A-Za-z0-9-]+-[0-9]+\/[A-Za-z0-9-]+$ || "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "develop" ]]; then
-            echo "Branch name is valid: $BRANCH_NAME"
-            echo "status=success" >> $GITHUB_ENV
+            echo "Branch name is valid"
+            exit 0
           else
-            echo "Invalid branch name: $BRANCH_NAME"
-            echo "status=failure" >> $GITHUB_ENV
+            echo "Invalid branch name"
+            exit 1
           fi
-
-      - name: Set GitHub Status (Failure)
-        if: env.status == 'failure'
-        run: |
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{
-              "state": "failure",
-              "context": "Branch Name Validation",
-              "description": "The branch name does not meet the required format. Allowed formats: <bugfix|hotfix|release>/<Ticket-Id>/<task-name>, master, develop."
-            }' "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
-
-      - name: Set GitHub Status (Success)
-        if: env.status == 'success'
-        run: |
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{
-              "state": "success",
-              "context": "Branch Name Validation",
-              "description": "The branch name is valid."
-            }' "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
